services:
  db:
    image: postgres:18-alpine
    container_name: pg_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tomcat-app
    depends_on:
        db:
          condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CATALINA_OPTS=-Dorg.apache.catalina.startup.HostConfig.deployXML=false
    ports:
        - "8080:8080"
    restart: unless-stopped
volumes:
  pgdata:
