#util properties
db.url=jdbc:postgresql://localhost:5432/new_bookstore
db.username=postgres
db.password=9534218
db.driver=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

#application properties
ioPath=data
unsoldBookMonth=7
autoCompleteRequest=true