#util properties
db.url=jdbc:postgresql://localhost:5432/new_bookstore
db.username=postgres
db.password=9534218
db.driver=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show-sql=true
hibernate.hbm2-ddl-auto=validate

#application properties
ioPath=data
unsoldBookMonth=7
autoCompleteRequest=true