#util properties
db.url=${DB_URL:jdbc:postgresql://localhost:5432/mydb}
db.username=${DB_USER:postgres}
db.password=${DB_PASSWORD:postgres}
db.driver=org.postgresql.Driver

liquibase.change-log-file=classpath:db/changelog/db.changelog-master.xml
liquibase.default-schema=public
liquibase.database-change-log-table-name=databasechangelog
liquibase.database-change-log-lock-table-name=databasechangeloglock

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show-sql=true
hibernate.hbm2-ddl-auto=validate

#jwt setting
jwt.secret=
jwt.expiration=60000
jwt.cookieName=refresh-jwt-cookie

#application properties
ioPath=data
unsoldBookMonth=7
autoCompleteRequest=true